### ISSUE TITLE
Cannot Repack .EMB File

### ISSUE THREAD

**Issue by montagesnmore** [DarioSamo/LibXenoverse#6]
Can you please show me what am I doing incorrect? I cannot repack a certain .EMB.

This is my command to unpack (which works): 

cpkpack.exe -x data2.cpk -d data2

However, when I repack I get this message:

cpkpack.exe -r data2\data\ui\sprite CURSOR,emb

Then it states:

---
## CPKPack

Parsed 2 files
Writing Tables...
Writing file 2/2
Rewriting Tables....
Done!

However when I play the game the .emb file didn't take effect. Can you please tell me am I missing a step or what I did wrong? 

Thanks!

**Comment by Melpontro** [comment]
You are only repacking the folder with the cursor.emb.
My personal workflow is the following.
Extract data2.cpk with
cpkpack.exe -x data2.cpk -d data2
Copy and paste the newly created data2 folder
rename it to data2_mod
replace whatever files you want
repack with
cpkpack.exe -r data2_mod data2.cpk

**Comment by EmilSayahi** [comment]
Shouldn't this be closed?

**Comment by DarioSamo** [comment]
Yep.
