### ISSUE TITLE
the cusxml.exe no found

### ISSUE THREAD

**Issue by Ark4n0** [DarioSamo/LibXenoverse#8]
Hi friend

I am trying to use the file cusxml.exe

But when I drag the file over the .exe nothing happens, the .xml file is not generated as occurs with emmxml.exe that this runs smoothly.

And another question, there is no file that can display the contents of the files .bcs?? I have seen that there are some libxenoverse files, called bcs.cpp, BCS.h, etcc. There are currently no executable to convert these files to xml ?? or some format more comfortable reading?

Thanx for attention.

**Comment by DarioSamo** [comment]
Those tools don't really actually do anything yet as the formats are not yet cracked. Both CUS and BCS just have some really barebones code that I worked on attempting to make some sense out of the format.

Not really much to report here, those formats just don't have any actual work yet.

**Comment by Ark4n0** [comment]
Thanks for the information, I hope that in the future have a function: D.
Best regards
