### ISSUE TITLE
CPKPack.exe Stopped working

### ISSUE THREAD

**Issue by MrUnusual** [DarioSamo/LibXenoverse#9]
I've noticed a lot of people having this problem. So.. I put CPKPack.exe, extract-data2.bat and repack-data-2.bat in Dragonball Xenoverse's directory folder. I run CPKPacker. exe and then as soon as cmd pops up I can see on the cmd where it says "Extracting File 1/743" but then in an instant, a window pops up saying CPKPack.exe has stopped working. Is there something I'm doing wrong? 0.o

**Comment by DarioSamo** [comment]
We've only seen this reported with the pirated versions of Dragon Ball Xenoverse. If you can confirm this happens with the Steam version then it will be looked into. (The file count would seem to indicate it's the latest Steam version)

A few things to try if it's a problem with the real version:
1) Make sure there's no existing data2 directory before extracting.
2) Put the LibXenoverse repository in a place with a short directory or no spaces. (e.g. C:/LibXenoverse)

**Comment by EmilSayahi** [comment]
Is this supposed to be closed?

**Comment by MrUnusual** [comment]
This can be closed sorry and thank you

**Comment by MrUnusual** [comment]
This can be closed sorry and thank you
